import "./globals.css";
import type { Metadata } from "next";
import { Outfit, Noto_Sans_KR } from "next/font/google";
import GoogleAnalytics from "@/components/GoogleAnalytics";

const notoSansKr = Noto_Sans_KR({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

export const outfit = Outfit({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang={process.env.NEXT_PUBLIC_LANG || "en"}
      className={notoSansKr.className}
    >
      <link
        rel="icon"
        href="/icon?<generated>"
        type="image/png"
        sizes="32x32"
      />
      <GoogleAnalytics
        GA_MEASUREMENT_ID={process.env.NEXT_PUBLIC_GA_ID as string}
      />
      <body>{children}</body>
    </html>
  );
}
